### ISSUE TITLE
Samsung Galaxy tab s4 screen rotation problem

### ISSUE THREAD

**Issue by anniekvandijk** [anniekvandijk/showringhelper-react-native#21]
Expo React native
    "expo": "^34.0.4",
    "native-base": "^2.13.5",
    "react": "^16.8.3",

Not responsive when orientation changes to landscape:
Not scrollable
Menu disappears

Change to portrait:
Bottom part of app is blank. Bottom navigation in middle of page.

**Comment by anniekvandijk** [comment]
Same problem on OnePlus6

**Comment by anniekvandijk** [comment]
Workaround?
https://stackoverflow.com/questions/29914572/react-native-flex-not-responding-to-orientation-change

**Comment by martin-ecatch** [comment]
@anniekvandijk FYI: changing the view dimensions in RN doesn't help, I tried that. It's because the container view (defined in the "shell app") has fixed height. AFAIK The only workaround at the moment is eject to ExpoKit, set SHOW_LOADING_VIEW_IN_SHELL_APP = false in AppConstants and build your app. You won't get splash screen, but orientation change is back. See my comment here https://github.com/expo/expo/issues/5033#issuecomment-523259295

**Comment by anniekvandijk** [comment]
@martin-ecatch Thank you for your reply. At this point I do not want to eject at this point. use Expo- Cli to develop for Android and IOS on my Windows machine. Works very nice when running the app at the same time on my Iphone and my Android to debug ;)

I think I look for another solution or wait for SDK 35. But, my app is in pre-release i can not make a release version without this working :( I hope there will be a fix soon.

**Comment by anniekvandijk** [comment]
@martin-ecatch workarround: 
How: in app.json change android->splash->resizeMode to "native" (instead of the default "contain).

**Comment by knilessew** [comment]
Fixed :)
